In [49]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [50]:
df= pd.read_csv("vistaara.movies.csv")

In [51]:
df.head()

,_id,tmdbId,__v,backdropPath,banner,cast[0],cast[1],cast[2],cast[3],cast[4],...,title,tmdbLastSyncedAt,trailerKey,trailerUrl,type,updatedAt,videoUrl,voteAverage,voteCount,year
0,6a3821f6555b83eb42e31975,1339713.0,0,/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg,https://image.tmdb.org/t/p/original/5lTZyuBTNO...,Michael Johnston,Inde Navarrette,Cooper Tomlinson,Megan Lawless,Andy Richter,...,Obsession,2026-06-21T18:24:16.863Z,gMC8kkwbIQQ,https://www.youtube.com/watch?v=gMC8kkwbIQQ,movie,2026-06-21T18:24:16.866Z,NaN,7.9,893,2026
1,6a3821f7555b83eb42e31976,936075.0,0,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,https://image.tmdb.org/t/p/original/ufSwlnECLo...,Jaafar Jackson,Colman Domingo,Nia Long,Juliano Krue Valdi,Miles Teller,...,Michael,2026-06-21T18:24:17.357Z,k-YAcjaLuSI,https://www.youtube.com/watch?v=k-YAcjaLuSI,movie,2026-06-21T18:24:17.358Z,NaN,8.7,2785,2026
2,6a3821f8555b83eb42e31977,931285.0,0,/laR2dpcNpbv83jdlRUNAYPPjH90.jpg,https://image.tmdb.org/t/p/original/laR2dpcNpb...,Karl Urban,Adeline Rudolph,Ludi Lin,Jessica McNamee,Lewis Tan,...,Mortal Kombat II,2026-06-21T18:24:17.844Z,zva2PQ-ud5Y,https://www.youtube.com/watch?v=zva2PQ-ud5Y,movie,2026-06-21T18:24:17.844Z,NaN,8.0,1532,2026
3,6a3821f8555b83eb42e31978,1392469.0,0,/vwvMQxD3MHHk2cQCuSyEdYktjUL.jpg,https://image.tmdb.org/t/p/original/vwvMQxD3MH...,Shahid Kapoor,Kriti Sanon,Rashmika Mandanna,Mark Bennington,Tiku Talsania,...,Cocktail 2,2026-06-22T11:28:48.355Z,NaN,NaN,movie,2026-06-22T11:28:48.357Z,NaN,5.0,4,2026
4,6a3821f9555b83eb42e31979,28322.0,0,/7TJjD2X9GTEqyLVIJKLS85J2V47.jpg,https://image.tmdb.org/t/p/original/7TJjD2X9GT...,Joe Dallesandro,Patrizia Behn,Gianni Macchia,Lorraine De Selle,Omero Capanna,...,Madness,2026-06-21T18:10:22.940Z,NaN,NaN,movie,2026-06-21T18:10:22.941Z,NaN,5.0,32,1980

In [52]:
df.columns

Index(['_id', 'tmdbId', '__v', 'backdropPath', 'banner', 'cast[0]', 'cast[1]',
       'cast[2]', 'cast[3]', 'cast[4]', 'cast[5]', 'cast[6]', 'cast[7]',
       'cast[8]', 'cast[9]', 'cast[10]', 'cast[11]', 'categories[0]',
       'categories[1]', 'categories[2]', 'categories[3]', 'categories[4]',
       'createdAt', 'description', 'duration', 'durationSeconds',
       'episodeCount', 'genre', 'genres[0]', 'genres[1]', 'genres[2]',
       'genres[3]', 'genres[4]', 'genres[5]', 'genres[6]', 'isFeatured',
       'posterPath', 'rating', 'releaseDate', 'source', 'thumbnail', 'title',
       'tmdbLastSyncedAt', 'trailerKey', 'trailerUrl', 'type', 'updatedAt',
       'videoUrl', 'voteAverage', 'voteCount', 'year'],
      dtype='object')

In [53]:
df.shape

(4805, 51)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4805 entries, 0 to 4804
Data columns (total 51 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               4805 non-null   object
 1   tmdbId            4802 non-null   float64
 2   __v               4805 non-null   int64
 3   backdropPath      4059 non-null   object
 4   banner            4805 non-null   object
 5   cast[0]           4680 non-null   object
 6   cast[1]           4599 non-null   object
 7   cast[2]           4448 non-null   object
 8   cast[3]           4284 non-null   object
 9   cast[4]           4028 non-null   object
 10  cast[5]           3822 non-null   object
 11  cast[6]           3560 non-null   object
 12  cast[7]           3325 non-null   object
 13  cast[8]           3043 non-null   object
 14  cast[9]           2767 non-null   object
 15  cast[10]          2506 non-null   object
 16  cast[11]          2302 non-null   object
 17  categories[0]     4805 non-null   object
 18  categories[1]     4805 non-null   object
 19  categories[2]     2452 non-null   object
 20  categories[3]     17 non-null     object
 21  categories[4]     15 non-null     object
 22  createdAt         4805 non-null   object
 23  description       4805 non-null   object
 24  duration          4413 non-null   object
 25  durationSeconds   4805 non-null   int64
 26  episodeCount      4805 non-null   int64
 27  genre             4805 non-null   object
 28  genres[0]         4580 non-null   object
 29  genres[1]         3534 non-null   object
 30  genres[2]         1680 non-null   object
 31  genres[3]         352 non-null    object
 32  genres[4]         75 non-null     object
 33  genres[5]         7 non-null      object
 34  genres[6]         1 non-null      object
 35  isFeatured        4805 non-null   bool
 36  posterPath        4795 non-null   object
 37  rating            4805 non-null   object
 38  releaseDate       4789 non-null   object
 39  source            4805 non-null   object
 40  thumbnail         4805 non-null   object
 41  title             4805 non-null   object
 42  tmdbLastSyncedAt  4802 non-null   object
 43  trailerKey        2173 non-null   object
 44  trailerUrl        2173 non-null   object
 45  type              4805 non-null   object
 46  updatedAt         4805 non-null   object
 47  videoUrl          3 non-null      object
 48  voteAverage       4805 non-null   float64
 49  voteCount         4805 non-null   int64
 50  year              4805 non-null   int64
dtypes: bool(1), float64(2), int64(5), object(43)
memory usage: 1.8+ MB

In [55]:
df.isnull().sum()

_id                    0
tmdbId                 3
__v                    0
backdropPath         746
banner                 0
cast[0]              125
cast[1]              206
cast[2]              357
cast[3]              521
cast[4]              777
cast[5]              983
cast[6]             1245
cast[7]             1480
cast[8]             1762
cast[9]             2038
cast[10]            2299
cast[11]            2503
categories[0]          0
categories[1]          0
categories[2]       2353
categories[3]       4788
categories[4]       4790
createdAt              0
description            0
duration             392
durationSeconds        0
episodeCount           0
genre                  0
genres[0]            225
genres[1]           1271
genres[2]           3125
genres[3]           4453
genres[4]           4730
genres[5]           4798
genres[6]           4804
isFeatured             0
posterPath            10
rating                 0
releaseDate           16
source                 0
thumbnail              0
title                  0
tmdbLastSyncedAt       3
trailerKey          2632
trailerUrl          2632
type                   0
updatedAt              0
videoUrl            4802
voteAverage            0
voteCount              0
year                   0
dtype: int64

In [56]:
df= df.drop_duplicates().reset_index(drop=True)

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df= df[['title', 'voteAverage','genres[0]','genres[1]','description','cast[0]','cast[1]','cast[2]']]
df

,title,voteAverage,genres[0],genres[1],description,cast[0],cast[1],cast[2]
0,Obsession,7.9,Horror,Thriller,"After breaking the mysterious ""One Wish Willow...",Michael Johnston,Inde Navarrette,Cooper Tomlinson
1,Michael,8.7,Music,Drama,"The story of Michael Jackson, one of the most ...",Jaafar Jackson,Colman Domingo,Nia Long
2,Mortal Kombat II,8.0,Action,Fantasy,The fan favorite champions—now joined by Johnn...,Karl Urban,Adeline Rudolph,Ludi Lin
3,Cocktail 2,5.0,Romance,Comedy,"After a decade together, Diya and Kunal's rela...",Shahid Kapoor,Kriti Sanon,Rashmika Mandanna
4,Madness,5.0,Thriller,Action,An escaped convicted murderer invades the cott...,Joe Dallesandro,Patrizia Behn,Gianni Macchia
...,...,...,...,...,...,...,...,...
4800,Little Things,0.0,Documentary,NaN,Rooted in personal memory and quiet reflection...,NaN,NaN,NaN
4801,Hearth and Home,0.0,Drama,NaN,"Alaav, is the story of Bhaveen Gossain, a 63-y...",Bhaveen Gossain,Savitri Gossain,Anita Kanwar
4802,Kesari Chapter 2,7.1,Drama,History,A courtroom drama inspired by the fight to exp...,Akshay Kumar,R. Madhavan,Ananya Panday
4803,Metro... In Dino,6.8,Drama,Romance,"Across a restless city, couples and strangers ...",Aditya Roy Kapur,Sara Ali Khan,Anupam Kher
4804,Kantara: Chapter 1,7.4,Thriller,Action,"Set before the legend of Kantara, a warrior ri...",Rishab Shetty,Rukmini Vasanth,Jayaram

In [59]:
df= df.dropna(subset=['cast[0]'])

In [60]:
df['genres[0]']= df['genres[0]'].fillna('')
df['genres[1]']= df['genres[1]'].fillna('')

df['description']= df['description'].fillna('')
df['cast[0]']= df['cast[0]'].fillna('')
df['cast[1]']= df['cast[1]'].fillna('')
df['cast[2]']= df['cast[2]'].fillna('')

In [61]:
import ast
df['genres'] = df[['genres[0]', 'genres[1]']].fillna('').apply(
    lambda x: ' '.join(x).strip(), axis=1
)

In [62]:
df['cast'] = df[['cast[0]', 'cast[1]', 'cast[2]']].fillna('').apply(
    lambda x: ' '.join(x).strip(), axis=1
)

In [63]:
df.head()

,title,voteAverage,genres[0],genres[1],description,cast[0],cast[1],cast[2],genres,cast
0,Obsession,7.9,Horror,Thriller,"After breaking the mysterious ""One Wish Willow...",Michael Johnston,Inde Navarrette,Cooper Tomlinson,Horror Thriller,Michael Johnston Inde Navarrette Cooper Tomlinson
1,Michael,8.7,Music,Drama,"The story of Michael Jackson, one of the most ...",Jaafar Jackson,Colman Domingo,Nia Long,Music Drama,Jaafar Jackson Colman Domingo Nia Long
2,Mortal Kombat II,8.0,Action,Fantasy,The fan favorite champions—now joined by Johnn...,Karl Urban,Adeline Rudolph,Ludi Lin,Action Fantasy,Karl Urban Adeline Rudolph Ludi Lin
3,Cocktail 2,5.0,Romance,Comedy,"After a decade together, Diya and Kunal's rela...",Shahid Kapoor,Kriti Sanon,Rashmika Mandanna,Romance Comedy,Shahid Kapoor Kriti Sanon Rashmika Mandanna
4,Madness,5.0,Thriller,Action,An escaped convicted murderer invades the cott...,Joe Dallesandro,Patrizia Behn,Gianni Macchia,Thriller Action,Joe Dallesandro Patrizia Behn Gianni Macchia

In [64]:
df['tags'] = df['description']+ " " + df['genres'] 

df.head()

,title,voteAverage,genres[0],genres[1],description,cast[0],cast[1],cast[2],genres,cast,tags
0,Obsession,7.9,Horror,Thriller,"After breaking the mysterious ""One Wish Willow...",Michael Johnston,Inde Navarrette,Cooper Tomlinson,Horror Thriller,Michael Johnston Inde Navarrette Cooper Tomlinson,"After breaking the mysterious ""One Wish Willow..."
1,Michael,8.7,Music,Drama,"The story of Michael Jackson, one of the most ...",Jaafar Jackson,Colman Domingo,Nia Long,Music Drama,Jaafar Jackson Colman Domingo Nia Long,"The story of Michael Jackson, one of the most ..."
2,Mortal Kombat II,8.0,Action,Fantasy,The fan favorite champions—now joined by Johnn...,Karl Urban,Adeline Rudolph,Ludi Lin,Action Fantasy,Karl Urban Adeline Rudolph Ludi Lin,The fan favorite champions—now joined by Johnn...
3,Cocktail 2,5.0,Romance,Comedy,"After a decade together, Diya and Kunal's rela...",Shahid Kapoor,Kriti Sanon,Rashmika Mandanna,Romance Comedy,Shahid Kapoor Kriti Sanon Rashmika Mandanna,"After a decade together, Diya and Kunal's rela..."
4,Madness,5.0,Thriller,Action,An escaped convicted murderer invades the cott...,Joe Dallesandro,Patrizia Behn,Gianni Macchia,Thriller Action,Joe Dallesandro Patrizia Behn Gianni Macchia,An escaped convicted murderer invades the cott...

In [65]:
df['tags'][1]

'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career. Music Drama'

In [66]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [67]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\VICTUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\VICTUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [68]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [69]:
def preprocess_text(text):
  text = str(text).lower()
  text = re.sub(r'[^a-zA-Z\s]', '', text)
  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [70]:
df['tags'] = df['tags'].apply(preprocess_text)

In [71]:
df['tags'][1]

'story michael jackson one influential artist world ever known life beyond music journey discovery extraordinary talent lead jackson five visionary artist whose creative ambition fueled relentless pursuit become biggest entertainer world highlighting life offstage iconic performance early solo career music drama'

In [72]:
df = df.reset_index(drop = True)

In [73]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Obsession                0
Michael                  1
Mortal Kombat II         2
Cocktail 2               3
Madness                  4
                      ...
Women                 4675
Hearth and Home       4676
Kesari Chapter 2      4677
Metro... In Dino      4678
Kantara: Chapter 1    4679
Length: 4680, dtype: int64

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['tags'])

tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 153707 stored elements and shape (4680, 50000)>

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

In [77]:
def recommend(title, n = 5):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [79]:
recommend('Toy Story 5' ,1)

36    Toy Story
Name: title, dtype: object